name: weather_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.5
  http: ^0.12.0+3
  flutter_spinkit: ^4.1.1
  intl: ^0.16.1
  recase: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Yantramanav-Regular
      fonts:
        - asset: fonts/Yantramanav-Regular.ttf
    - family: JosefinSans-Light
      fonts:
        - asset: fonts/JosefinSans-Light.ttf